Add  for decoding x-www-form-urlencoded data
scotty-web/scotty pull request #216
Opened 2018-03-18 02:44 UTC by mitchellwrosen

Here ya go if you'd like it - decoding `x-www-form-urlencoded` request bodies a la `jsonData`

2023-07-07 01:58 UTC, ocramz approved these changes
👍

2023-09-10 20:57 UTC, ocramz commented
@mitchellwrosen I've fixed the conflicts, now waiting for CI and we're good to merge

2023-09-24 10:13 UTC, ocramz requested changes
http-api-data import is missing.

2023-09-24 10:13 UTC, ocramz commented on Web/Scotty/Action.hs
> +import qualified Web.FormUrlEncoded         as F
I've just noticed that CI fails because this module is not in scope. @mitchellwrosen could you add the 'http-api-data' import in the cabal file?

2023-09-25 00:17 UTC, mitchellwrosen commented
@ocramz Sorry but I'm not sure I have the context or bandwidth to dedicate to this 5 year old PR of mine. I'm not a scotty user :(

I will note that the commit I made looks rather different than the PR in its current form.

Here is my commit: https://github.com/scotty-web/scotty/pull/216/commits/2a7db35ed3ba02cd84a42d4c3f5c325f4d67dad9

I think the merge commit you made into this branch 2 weeks ago has accidentally added some unwanted stuff, somehow:

https://github.com/scotty-web/scotty/pull/216/commits/4ea5e7fdc93abe8fc8ec8dda10851ab06549758d

2023-10-03 09:19 UTC, closed without merging

2023-10-03 09:19 UTC, ocramz commented
@mitchellwrosen  apologies, I must have made a mistake while fixing conflicts. Closing this for now and resuming at #321