add Web.Scotty.Trans.Strict
scotty-web/scotty pull request #334
Opened 2023-10-12 08:42 UTC by fumieval

One major annoyance with scotty is that some functions unnecessarily take/return lazy Text.

This PR adds a new module `Web.Scotty.Trans.Strict` which uses strict Text instead

2023-10-13 19:24 UTC, ocramz commented
Maybe a minor thing, but elsewhere `.Trans.Strict` refers to the evaluation of the effect being non-lazy: https://hackage.haskell.org/package/transformers-0.6.1.1/docs/Control-Monad-Trans-State-Strict.html . Here we have the added complication that ScottyT is not MonadTrans :D

2023-10-15 06:03 UTC, ocramz requested changes
It looks good so far, thank you for this.
Now CI fails because of a wrong Text import in one of the example programs.
Once CI turns green we are ready to merge this 👍

2023-10-15 06:05 UTC, ocramz commented on changelog.md
> +* add `Web.Scotty.Trans.Strict`
as well as `.Trans.Lazy`, which use strict and lazy text respectively

2023-10-15 06:40 UTC, fumieval commented on Web/Scotty/Trans/Strict.hs
> +-- the comments on each of these functions for more information.
Sure

2023-10-15 06:41 UTC, fumieval commented
Thanks for reviewing this. I've just rebased the branch and fixed the problems you pointed out

2023-10-15 07:41 UTC, ocramz approved these changes
Very nice 👍

2023-10-15 07:42 UTC, merged