Feature/user sessions
scotty-web/scotty pull request #405
Opened 2024-12-03 21:02 UTC by tusharad

This PR introduces user session management for the Scotty, addressing the requirements outlined in issue #317. The implementation draws inspiration from the [Scotty Session library](https://hackage.haskell.org/package/scotty-session-0.0.5/docs/Web-Scotty-Session.html#t:ScottySM).

Checklist:
- [x] Updated the changelog to reflect the new features.
- [x] Exposed the session management module via Web.Scotty.
- [x] Added comprehensive Haddock documentation for all public functions and types.
- [x] Included a practical example in the Example directory to demonstrate usage.
- [x] Developed test cases to ensure the robustness and reliability of the session management feature.

Please let me know if there are any further changes or additions you need. Thank you for reviewing this PR!

@ocramz

2024-12-04 04:14 UTC, ocramz commented
@tusharad Thank you! I think this is a very good PR. Just couple of minor remarks on documentation and a return type.

2024-12-31 10:40 UTC, ocramz commented
Hi @tusharad , hope you're doing well! I was wondering whether you need any help to land this PR? Please let us know :)

2024-12-31 10:47 UTC, tusharad commented
Hi @ocramz,

I believe there might have been a misunderstanding. Since you self-assigned this task, I assumed you would be implementing some of the changes yourself.

> "Just a couple of minor remarks on documentation and a return type."

Could you please elaborate on the specific return type and areas in the documentation you’d like to see revised? This will help me address your feedback more effectively.

Thanks!

2024-12-31 10:54 UTC, ocramz commented
Hi @tusharad , yes apologies about that!  

The return type I was mentioning is that of `getUserSession`, to distinguish the "no session" case from "expired". But I'm open to keeping this as it is with a strong enough argument :)

2024-12-31 11:29 UTC, tusharad commented
Here’s an improved and more polished version of your PR reply:

Hi @ocramz ,

Thank you for the feedback! In the latest update, I’ve replaced Nothing with Either and introduced a new type called SessionStatus, which can represent SessionExpired or SessionNotFound. Please let me know if there’s anything else you’d like to adjust or further refine. I appreciate your input!

2025-01-04 01:28 UTC, ocramz requested changes
A few outstanding comments, but mainly:
* missing ActionM specialized Session functions
* changelog entry with issue number
* Session module header with correct authors and copyright

Optional but nice to have : 
* add a mention of the new Session functionality in the README

2025-01-04 01:28 UTC, ocramz commented on Web/Scotty.hs
As far as I can see, this file (Web.Scotty) is missing the specialized versions of the `Session` functions, returning in the `ActionM` monad.  See e.g. https://hackage.haskell.org/package/scotty-0.22/docs/src/Web.Scotty.html#request

2025-01-04 08:27 UTC, tusharad commented
Thanks for the review @ocramz!

- [x] Added ActionM specialized Session functions. I noticed the cookie functions don't have ActionM versions—should I open a separate issue for this?
- [x] Updated changelog entry with issue number
- [x] Updated session module header with correct authors and copyright.
- [ ] I missed mentioning sessions in README :( 
- [x] I also squeezed in optional expiration time as argument in createUsersSession.

Do let me know in anything else is required. Thanks again!

2025-01-04 10:18 UTC, ocramz commented
@tusharad Thanks for the revision! 

> the cookie functions don't have ActionM versions—should I open a separate issue for this?

Yes please, open a new ticket for this.

2025-01-04 18:30 UTC, ocramz commented
@tusharad thanks! There's still time to add a line to the README, in the Examples section :)

2025-01-07 08:37 UTC, tusharad commented
> There's still time to add a line to the README

@ocramz done :)

2025-01-07 08:46 UTC, ocramz approved these changes
Thank you @tusharad ! Great work. 👍

2025-01-07 08:47 UTC, merged